#!/usr/bin/env bash

VESTING_TEZ_CODE="$(cat ../contracts/vesting_tez.tz | sed '/code/,$!d' | sed 's/^.\{4\}/ /')"
VESTING_TEZ_CODE_WITHOUT_SEMICOLON=${VESTING_TEZ_CODE%;}

read -r -d '' MLIGO_CODE << EOM
(* Automatically generated by ./mk_vesting_tez.mligo.sh *)

type vesting_tez_param =
  SetDelegate of key_hash option
| Vest of nat

type wrapped = address * address
type schedule_seconds = nat * nat
type schedule = timestamp * schedule_seconds
type vested_schedule = nat * schedule
type vesting_tez_storage = wrapped * vested_schedule

let vesting_tez_main (x : vesting_tez_param * vesting_tez_storage) : operation list * vesting_tez_storage =
  [%Michelson ({|
$VESTING_TEZ_CODE_WITHOUT_SEMICOLON
  |} : vesting_tez_param * vesting_tez_storage -> operation list * vesting_tez_storage) ] x
EOM

echo "$MLIGO_CODE" > vesting_tez.mligo

